#!/bin/sh

# Copyright (c) 2016 Thomas De Schampheleire <thomas.de.schampheleire@gmail.com>
# Manually coded based on sheet music at
# http://starwars.wikia.com/wiki/The_Imperial_March?file=Imperial%20March.png
# See file LICENSE for license information.

. $(dirname $(readlink -f $0))/dbeep.inc.sh

note4  ${G[3]}
note4  ${G[3]}
note4  ${G[3]}
note8d ${Eb[3]}
note16 ${Bb[3]}

note4  ${G[3]}
note8d ${Eb[3]}
note16 ${Bb[3]}
note2  ${G[3]}

note4  ${D[4]}
note4  ${D[4]}
note4  ${D[4]}
note8d ${Eb[4]}
note16 ${Bb[3]}

note4  ${Gb[3]}
note8d ${Eb[3]}
note16 ${Bb[3]}
note2  ${G[3]}

note4  ${G[4]}
note8d ${G[3]}
note16 ${G[3]}
note4  ${G[4]}
note8d ${Fs[4]}
note16 ${F[4]}

note16 ${E[4]}
note16 ${Ds[4]}
note   ${E[4]} $L8 $L4 # extra pause
note8  ${Gs[3]}
note4  ${Cs[4]}
note8d ${C[4]}
note16 ${B[3]}

note16 ${Bb[3]}
note16 ${A[3]}
note   ${Bb[3]} $L8 $L4 # extra pause
note8  ${Eb[3]}
note4  ${Gb[3]}
note8d ${Eb[3]}
note16 ${G[3]}

note4  ${Bb[3]}
note8d ${G[3]}
note16 ${Bb[3]}
note2  ${D[4]}

note4  ${G[4]}
note8d ${G[3]}
note16 ${G[3]}
note4  ${G[4]}
note8d ${Fs[4]}
note16 ${F[4]}

note16 ${E[4]}
note16 ${Ds[4]}
note   ${E[4]} $L8 $L4 # extra pause
note8  ${Gs[3]}
note4  ${Cs[4]}
note8d ${C[4]}
note16 ${B[3]}

note16 ${Bb[3]}
note16 ${A[3]}
note   ${Bb[3]} $L8 $L4 # extra pause
note8  ${Eb[3]}
note4  ${Gb[3]}
note8d ${Eb[3]}
note16 ${Bb[3]}

note4  ${G[3]}
note8d ${Eb[3]}
note16 ${Bb[3]}
note2  ${G[3]}

dbeep
