#!/bin/sh

# Copyright (c) 2016 Thomas De Schampheleire <thomas.de.schampheleire@gmail.com>
# Manually coded based on sheet music at
# http://pop-sheet-music.com/Files/4a34e9740c764a1dc131af7ed130720f.pdf
# See file LICENSE for license information.

. $(dirname $(readlink -f $0))/dbeep.inc.sh

tnote 8  ${D[3]}
tnote 8  ${D[3]}
tnote 8  ${D[3]}

lnote 2  ${G[3]}
lnote 2  ${D[4]}

tnote 8  ${C[4]}
tnote 8  ${B[3]}
tnote 8  ${A[3]}
lnote 2  ${G[4]}
lnote 4  ${D[4]}

tnote 8  ${C[4]}
tnote 8  ${B[3]}
tnote 8  ${A[3]}
lnote 2  ${G[4]}
lnote 4  ${D[4]}

tnote 8  ${C[4]}
tnote 8  ${B[3]}
tnote 8  ${C[4]}
ldnote 2  ${A[3]} # a bit longer than on score
tnote 4  ${D[3]}
tnote 8  ${D[3]}

lnote 2  ${G[3]}
lnote 2  ${D[4]}

tnote 8  ${C[4]}
tnote 8  ${B[3]}
tnote 8  ${A[3]}
lnote 2  ${G[4]}
lnote 4  ${D[4]}

tnote 8  ${C[4]}
tnote 8  ${B[3]}
tnote 8  ${A[3]}
lnote 2  ${G[4]}
lnote 4  ${D[4]}

tnote 8  ${C[4]}
tnote 8  ${B[3]}
tnote 8  ${C[4]}
ldnote 2  ${A[3]} # a bit longer than on score
tnote 4  ${D[3]}
tnote 8  ${D[3]}

ldnote 4  ${E[3]}
lnote 8  ${E[3]}
lnote 8  ${C[4]}
lnote 8  ${B[3]}
lnote 8  ${A[3]}
lnote 8  ${G[3]}

tnote 8  ${G[3]}
tnote 8  ${A[3]}
tnote 8  ${B[3]}
tnote 4  ${A[3]}
tnote 8  ${E[3]}
lnote 4  ${Fs[3]}
tnote 4  ${D[3]}
tnote 8  ${D[3]}

ldnote 4  ${E[3]}
lnote 8  ${E[3]}
lnote 8  ${C[4]}
lnote 8  ${B[3]}
lnote 8  ${A[3]}
lnote 8  ${G[3]}

ldnote 8  ${D[4]}
lnote 16 ${A[3]}
lnote 2  ${A[3]}
tnote 4  ${D[3]}
tnote 8  ${D[3]}

ldnote 4  ${E[3]}
lnote 8  ${E[3]}
lnote 8  ${C[4]}
lnote 8  ${B[3]}
lnote 8  ${A[3]}
lnote 8  ${G[3]}

tnote 8  ${G[3]}
tnote 8  ${A[3]}
tnote 8  ${B[3]}
tnote 4  ${A[3]}
tnote 8  ${E[3]}
lnote 4  ${Fs[3]}
tnote 4  ${D[4]}
tnote 8  ${D[4]}

ltnote 4  ${G[4]}
tnote 8  ${F[4]}
ltnote 4  ${E[4]}
tnote 8  ${D[4]}
ltnote 4  ${C[4]}
tnote 8  ${Bb[3]}
ltnote 4  ${A[3]}
tnote 8  ${G[3]}

# this measure is a bit odd on the score, I simplified it a bit.
lnote 4  ${D[4]}
 note    ${A[3]} $((${L[2]} * 8 / 6)) $((${L[2]} * 1 / 6 + ${L[8]})) # extra pause
tnote 8  ${D[3]}
tnote 8  ${D[3]}
tnote 8  ${D[3]}

lnote 2  ${G[3]}
lnote 2  ${D[4]}

tnote 8  ${C[4]}
tnote 8  ${B[3]}
tnote 8  ${A[3]}
lnote 2  ${G[4]}
lnote 4  ${D[4]}

tnote 8  ${C[4]}
tnote 8  ${B[3]}
tnote 8  ${A[3]}
lnote 2  ${G[4]}
lnote 4  ${D[4]}

tnote 8  ${C[4]}
tnote 8  ${B[3]}
tnote 8  ${C[4]}
ldnote 2  ${A[3]} # a bit longer than on score
tnote 4  ${D[3]}
tnote 8  ${D[3]}

lnote 2  ${G[3]}
lnote 2  ${D[4]}

tnote 8  ${C[4]}
tnote 8  ${B[3]}
tnote 8  ${A[3]}
lnote 2  ${G[4]}
lnote 4  ${D[4]}

tnote 8  ${C[4]}
tnote 8  ${B[3]}
tnote 8  ${A[3]}
lnote 2  ${G[4]}
lnote 4  ${D[4]}

tnote 8  ${C[4]}
tnote 8  ${B[3]}
tnote 8  ${C[4]}
ldnote 2  ${A[3]} # a bit longer than on score

# leave out the strange ending of the score

dbeep
