#!/bin/bash

# Tune found at https://www.reddit.com/r/linux/comments/18h8v5/does_anyone_have_or_know_a_source_for_beep_scripts/
# dbeeptized by Thomas De Schampheleire <thomas.de.schampheleire@gmail.com>
# See file LICENSE for license information.

. $(dirname $(readlink -f $0))/dbeep.inc.sh

f=3000;
while [ $f -gt 400 ]; do
    note $f 5;
    f=$(( f * 97 / 100));
done

dbeep
