#!/bin/bash

# Copyright (c) 2016 Thomas De Schampheleire <thomas.de.schampheleire@gmail.com>
# Manually coded based on sheet music at
# http://starwars.wikia.com/wiki/The_Imperial_March?file=Imperial%20March.png
# See file LICENSE for license information.

. $(dirname $(readlink -f $0))/dbeep.inc.sh

nnote 4  ${G[3]}
nnote 4  ${G[3]}
nnote 4  ${G[3]}
dnote 8 ${Eb[3]}
nnote 16 ${Bb[3]}

nnote 4  ${G[3]}
dnote 8 ${Eb[3]}
nnote 16 ${Bb[3]}
nnote 2  ${G[3]}

nnote 4  ${D[4]}
nnote 4  ${D[4]}
nnote 4  ${D[4]}
dnote 8 ${Eb[4]}
nnote 16 ${Bb[3]}

nnote 4  ${Gb[3]}
dnote 8 ${Eb[3]}
nnote 16 ${Bb[3]}
nnote 2  ${G[3]}

nnote 4  ${G[4]}
dnote 8 ${G[3]}
nnote 16 ${G[3]}
nnote 4  ${G[4]}
dnote 8 ${Fs[4]}
nnote 16 ${F[4]}

nnote 16 ${E[4]}
nnote 16 ${Ds[4]}
 note   ${E[4]} ${L[8]} ${L[4]} # extra pause
nnote 8  ${Gs[3]}
nnote 4  ${Cs[4]}
dnote 8 ${C[4]}
nnote 16 ${B[3]}

nnote 16 ${Bb[3]}
nnote 16 ${A[3]}
 note   ${Bb[3]} ${L[8]} ${L[4]} # extra pause
nnote 8  ${Eb[3]}
nnote 4  ${Gb[3]}
dnote 8 ${Eb[3]}
nnote 16 ${G[3]}

nnote 4  ${Bb[3]}
dnote 8 ${G[3]}
nnote 16 ${Bb[3]}
nnote 2  ${D[4]}

nnote 4  ${G[4]}
dnote 8 ${G[3]}
nnote 16 ${G[3]}
nnote 4  ${G[4]}
dnote 8 ${Fs[4]}
nnote 16 ${F[4]}

nnote 16 ${E[4]}
nnote 16 ${Ds[4]}
 note   ${E[4]} ${L[8]} ${L[4]} # extra pause
nnote 8  ${Gs[3]}
nnote 4  ${Cs[4]}
dnote 8 ${C[4]}
nnote 16 ${B[3]}

nnote 16 ${Bb[3]}
nnote 16 ${A[3]}
 note   ${Bb[3]} ${L[8]} ${L[4]} # extra pause
nnote 8  ${Eb[3]}
nnote 4  ${Gb[3]}
dnote 8 ${Eb[3]}
nnote 16 ${Bb[3]}

nnote 4  ${G[3]}
dnote 8 ${Eb[3]}
nnote 16 ${Bb[3]}
nnote 2  ${G[3]}

dbeep
